name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: lint_and_format
  runs-on: ubuntu-latest
  strategy:
    matrix:
      python-version: [3.10, 3.11, 3.12, 3.13]
  
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        cache-dependency-path: .github/workflows/ci.yml

    - name: Install project dependencies
      run: uv sync --locked --all-extras --dev

    - name: Check code formatting
      run: uv run ruff format --check .
    
    - name: Lint code
      run: uv run ruff check .